# The URL the site will be built for
base_url = "https://www.stackoverflowed.com"
title = "Stack Overflowed"
description = "Stack Overflowed has nothing to do with Stack Overflow."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Minify HTML output
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
ogimage = "favicons/ogimage.png"
email_address = "info@stackoverflowed.com"
